### ISSUE TITLE
Rows and columns in metis() and metis_one_level()

### ISSUE THREAD

**Issue by NilsWinter** [mdeff/cnn_graph#2]
I was trying to run the mnist.ipynb notebook but encountered the following error:

---------------------------------------------------------------------------------------------------------

> IndexError                                Traceback (most recent call last)
> <ipython-input-3-21bcff5c7c59> in <module>()
>      44 A = grid_graph(28, corners=False)
>      45 A = graph.replace_random_edges(A, 0)
> ---> 46 L, perm = coarsen(A, FLAGS.coarsening_levels)
>      47 print('Execution time: {:.2f}s'.format(time.process_time() - t_start))
>      48 graph.plot_spectrum(L)
> 
> <ipython-input-3-21bcff5c7c59> in coarsen(A, levels)
>      17
>      18 def coarsen(A, levels):
> ---> 19     graphs, parents = coarsening.metis(A, levels)
>      20     perms = coarsening.compute_perm(parents)
>      21
> 
> /home/nils/scripts/graph_cnn/cnn_graph-master/coarsening.py in metis(W, levels, rid)
>      51         vv = val
>      52
> ---> 53         cluster_id = metis_one_level(cc,rr,vv,rid,weights) # cc is ordered
>      54
>      55         parents.append(cluster_id)
> 
> /home/nils/scripts/graph_cnn/cnn_graph-master/coarsening.py in metis_one_level(rr, cc, vv, rid, weights)
>     118             for jj in range(rowlength[tid]):
>     119                 nid = cc[rs+jj]
> --> 120                 if marked[nid]:
>     121                     tval = 0.0
>     122                 else:
> 
> IndexError: index 783 is out of bounds for axis 0 with size 783

----------------------------------------------------------------------------------------------------------

When I was trying to find the error, I noticed that something with the assignment of the row and column indices in the metis() function seems strange since the row indices are assigned to the variable "cc" and the column indices are assigned to the variable "rr". When the indices are passed to the function metis_one_level(), I noticed that metis_one_level() takes the variables in the following order: metis_one_level(rr,cc,vv,rid,weights). So here it seems as if the rows and columns are in the wrong order. In any way, when I change that, the mnist script runs smoothly without the index error. Maybe you know more and could shed some light on that since I don't know if changing rows and columns is a good idea.

----------------------------------------------------------------------------------------------------------
```
# PAIR THE VERTICES AND CONSTRUCT THE ROOT VECTOR
idx_row, idx_col, val = scipy.sparse.find(W)
cc = idx_row
rr = idx_col
vv = val
       
cluster_id = metis_one_level(cc,rr,vv,rid,weights) # cc is ordered
```

----------------------------------------------------------------------------------------------------------

Additionally, I've tried to insert my own data which is a correlation matrix (which basically is an adjacency matrix) but am not exactly sure at which point in the code I should do that. My idea was to build the grid graph, just changing the size of it from 28 to 160 and then continue with the script. Of course I would exchange the MNIST data with mine. Does that make sense? Do I need to build the grid even if I already have an adjacency matrix? Thanks a lot for your help!

**Comment by mdeff** [comment]
Thanks for reporting ! :) The problem was indeed that `scipy.sparse.find()` does not return the rows in order, as expected by the algorithm (maybe it did in the past as I did never encounter this issue). Nevertheless I've introduced an explicit ordering in commit a7afa1f9f217f303cfc3fe80599147476a4764ab. Let me know if it works for you.

There was indeed a naming issue with `rr` and `cc`, no need to exchange them. But it would be harmless to do so as the adjacency matrix is symmetric.

**Comment by mdeff** [comment]
Regarding usage, you do not need to build or use the grid if you have an adjacency matrix. The grid is used to construct the adjacency matrix for MNIST, because images reside on a 2D grid. So that the graph for MNIST is a lattice. But you have a graph already ! :)

Let me create a notebook as an usage example, where you would just have to give your adjacency and data matrices, set the hyper-parameters, and run it.

**Comment by NilsWinter** [comment]
Thanks for answering!
Your commit indeed fixed it. Now it works like a charm. :)

Of course, a notebook as usage example would be more than great. Thanks a lot!
I'm closing this issue now. :)
